// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmE3tFfel9gOMNk0sDXDCVlk63-gseRfE',
    appId: '1:126983021915:web:aa005026375af52836a67e',
    messagingSenderId: '126983021915',
    projectId: 'myfarm-a3bec',
    authDomain: 'myfarm-a3bec.firebaseapp.com',
    storageBucket: 'myfarm-a3bec.firebasestorage.app',
    measurementId: 'G-7JSWXHLH4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwfSiW3cTSlceB6x-iPRNgrr38D7FhnC4',
    appId: '1:126983021915:android:8abb4d7cf9ea7b1436a67e',
    messagingSenderId: '126983021915',
    projectId: 'myfarm-a3bec',
    storageBucket: 'myfarm-a3bec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpUv2l2aKifmd2m-YZF9xb9P3H4Ak9fs0',
    appId: '1:126983021915:ios:2c5dd9d1c8f3429e36a67e',
    messagingSenderId: '126983021915',
    projectId: 'myfarm-a3bec',
    storageBucket: 'myfarm-a3bec.firebasestorage.app',
    iosBundleId: 'com.example.tryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpUv2l2aKifmd2m-YZF9xb9P3H4Ak9fs0',
    appId: '1:126983021915:ios:2c5dd9d1c8f3429e36a67e',
    messagingSenderId: '126983021915',
    projectId: 'myfarm-a3bec',
    storageBucket: 'myfarm-a3bec.firebasestorage.app',
    iosBundleId: 'com.example.tryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmE3tFfel9gOMNk0sDXDCVlk63-gseRfE',
    appId: '1:126983021915:web:4607c2a25a03a87e36a67e',
    messagingSenderId: '126983021915',
    projectId: 'myfarm-a3bec',
    authDomain: 'myfarm-a3bec.firebaseapp.com',
    storageBucket: 'myfarm-a3bec.firebasestorage.app',
    measurementId: 'G-SRJ8MX59BN',
  );
}
